### ISSUE TITLE
Commands not working

### ISSUE THREAD

**Issue by OS-Scratch** [CharsargCodeDevelopment/ScratchOS#1]
Hi, maybe you remember my issue on Scratch. I'm georgek0. My issue is the commands not working and a giant window displaying "test.txt" or something like that covering an other window. I also don't get an output.

**Comment by CharsargCodeDevelopment** [comment]
The windows you are seeing a part of the filesystem lists.
I forgot to hide them.
I will patch this after I upload V0.6.0

**Comment by CharsargCodeDevelopment** [comment]
I have pushed a bugfix to scratch.

**Comment by CharsargCodeDevelopment** [comment]
Bug has been fixed

**Comment by OS-Scratch** [comment]
Thanks!
